Algoritmo "Atividade 1 - 1"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/06/2023
Var
// Seção de Declarações das variáveis 
area: real
raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o raio do circulo: ")
leia (raio)
area <- pi * raio * raio
escreval("A área deste círculo é: ", area)

Fimalgoritmo