Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
base, altura, resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a base: ")
leia(base)
escreval("Digite a altura: ")
leia(altura)
resultado <- base * altura
escreva("A área deste retângulo é: ", resultado)


Fimalgoritmo